#pragma once

enum RenderPassID {
    PASS_SETUP = 0,
    PASS_RENDERGRASSINST,
    PASS_RENDERSHADOW,
    PASS_RENDERSHADOWFFE,
    PASS_RENDERLAND,
    PASS_RENDERLANDREFL,
    PASS_RENDERSTATICSEXTERIOR,
    PASS_RENDERSTATICSINTERIOR,
    PASS_RENDERSKY,
    PASS_RENDERCLOUDS,
    PASS_RENDERWATER,
    PASS_RENDERUNDERWATER,
    PASS_RENDERCAUSTICS,
    PASS_BLENDMGE,
    PASS_DEBUGSHADOW,
    PASS_PLAYERWAVE,
    PASS_WAVESTEP,
    PASS_WORKAROUND,
    PASS_RENDERSHADOW_INDEXED,
    PASS_RENDERSHADOWFFE_INDEXED
};

enum RenderShadowMapID {
    PASS_SHADOWSTENCIL = 0,
    PASS_RENDERSHADOWMAP,
    PASS_RENDERSTATICSHADOWMAP
};

enum RenderDepthID {
    PASS_CLEARDEPTH = 0,
    PASS_RENDERMWDEPTH,
    PASS_RENDERLANDDEPTH,
    PASS_RENDERSTATICSDEPTH,
    PASS_RENDERGRASSDEPTHINST,
    PASS_NATIVEDEPTH_REPLACE,
    PASS_NATIVEDEPTH_MERGE,
    PASS_RENDERMWDEPTH_INDEXED
};

static const int SIZEOFSTATICVERT = 28;
static const int SIZEOFGRASSVERT = 20;
